n1 = float(input('Digite a nota do 1° bimestre: '))
n2 = float(input('Digite a nota do 2° bimestre: '))
n3 = float(input('Digite a nota do 3° bimestre: '))
n4 = float(input('Digite a nota do 4° bimestre: '))
m = ((n1 + n2 + n3 + n4) / 4)
print('Sua média final foi: {:.2f}'.format(m))